---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: object-quota
  namespace: myspace
spec:
  hard:
    configmaps: "2"
    persistentvolumeclaims: "4"
    replicationcontrollers: "20"
    secrets: "2"
    services: "1"
    services.loadbalancers: "2"
